[chain]
id = 1
name = "ZionLayer Devnet"
block_time = "2s"

[consensus]
type = "zionbft"
min_validator_stake = "10000000000000000000000"  # 10,000 AGC

[rpc]
port = 8545
cors_origins = ["*"]

[p2p]
port = 9000
max_peers = 50

[data]
dir = "./data"
db = "leveldb"

[log]
level = "info"
format = "json"

[genesis]
# Prefunded devnet accounts
[[genesis.accounts]]
address = "0xDevnetFaucet0000000000000000000000001"
balance = "100000000000000000000000000"  # 100M AGC

[[genesis.accounts]]
address = "0xValidator1000000000000000000000001"
balance = "1000000000000000000000000"    # 1M AGC
